[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.post-build]
dependencies = ["build"]
script = [
    "copy /y \"target\\i686-pc-windows-msvc\\release\\samp_rs_asi.dll\" \"target\\i686-pc-windows-msvc\\release\\samp_rs_asi.asi\""
]

[tasks.default]
alias = "post-build"
